# Generated by Django 4.2.1 on 2023-08-06 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CARGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CHAVES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=4)),
                ('Numeracao_Armario', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='CURSOSENAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Codigo', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='KITS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=4)),
                ('Numeracao_Armario', models.CharField(max_length=4)),
                ('Tipo_de_Kit', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PREDIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Endereco', models.CharField(max_length=60, null=True)),
                ('Telefone', models.CharField(max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_SALA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Sala', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SALAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.CharField(max_length=4)),
                ('Tipo_de_Kit', models.CharField(max_length=4)),
                ('Ocupada', models.BooleanField(default=False)),
                ('Esta_ativa', models.BooleanField(default=True, null=True)),
                ('Tipo_Sala_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.tipo_sala')),
            ],
        ),
        migrations.CreateModel(
            name='FUNCIONARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=14, unique=True)),
                ('Matricula', models.CharField(max_length=15, unique=True)),
                ('Telefone', models.CharField(max_length=11)),
                ('Cargo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.cargo')),
                ('Curso_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.cursosenac')),
                ('User_FK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EMPRESTIMOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horario_Recepcao', models.DateTimeField()),
                ('Horario_Devolucao', models.DateTimeField(blank=True, null=True)),
                ('Esta_Emprestado', models.BooleanField(default=False)),
                ('Chaves_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.chaves')),
                ('Funcionario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.funcionario')),
                ('Kit_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.kits')),
            ],
        ),
        migrations.AddField(
            model_name='cursosenac',
            name='Predio_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.predio'),
        ),
        migrations.AddField(
            model_name='chaves',
            name='Salas_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.salas'),
        ),
        migrations.CreateModel(
            name='AGENDAMENTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horario_inicio', models.DateTimeField()),
                ('Horario_fim', models.DateTimeField()),
                ('Kit', models.BooleanField(default=False)),
                ('EstaAgendado', models.BooleanField(default=False)),
                ('Funcionario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.funcionario')),
                ('Salas_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.salas')),
            ],
        ),
    ]
