# Generated by Django 5.1.4 on 2025-03-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cursosenac',
            table='CURSOS',
        ),
        migrations.AlterModelTable(
            name='predio',
            table='PREDIOS',
        ),
    ]
