# Generated by Django 4.2.1 on 2023-06-06 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BancoDeDados', '0006_remove_agendamento_kit_fk_agendamento_kit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='User_FK',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
