# Generated by Django 4.2.1 on 2023-06-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0007_alter_funcionario_user_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='PREDIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='Chaves_FK',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='Funcionario_FK',
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='Kit_FK',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='Cargo_FK',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='Curso_FK',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='User_FK',
        ),
        migrations.DeleteModel(
            name='AGENDAMENTO',
        ),
        migrations.DeleteModel(
            name='CURSOSENAC',
        ),
        migrations.DeleteModel(
            name='EMPRESTIMOS',
        ),
        migrations.DeleteModel(
            name='FUNCIONARIO',
        ),
    ]
