# Generated by Django 4.2.1 on 2023-06-06 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BancoDeDados', '0008_predio_remove_emprestimos_chaves_fk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CURSOSENAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=20)),
                ('Codigo', models.CharField(max_length=8)),
                ('Predio_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.predio')),
            ],
        ),
        migrations.CreateModel(
            name='FUNCIONARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF', models.CharField(max_length=14)),
                ('Matricula', models.CharField(max_length=15)),
                ('Telefone', models.CharField(max_length=11)),
                ('Cargo_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.cargo')),
                ('Curso_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.cursosenac')),
                ('User_FK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EMPRESTIMOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horario_Recepcao', models.DateTimeField()),
                ('Horario_Devolucao', models.DateTimeField(blank=True, null=True)),
                ('Esta_Emprestado', models.BooleanField(default=True)),
                ('Chaves_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.chaves')),
                ('Funcionario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.funcionario')),
                ('Kit_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.kits')),
            ],
        ),
        migrations.CreateModel(
            name='AGENDAMENTO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Horario_inicio', models.DateTimeField()),
                ('Horario_fim', models.DateTimeField()),
                ('Kit', models.BooleanField(default=False)),
                ('Agendado', models.BooleanField(default=False)),
                ('Curso_FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.cursosenac')),
                ('Funcionario_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.funcionario')),
                ('Salas_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.salas')),
            ],
        ),
    ]
