# Generated by Django 4.2.1 on 2023-06-06 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0009_cursosenac_funcionario_emprestimos_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='Curso_FK',
        ),
    ]
