# Generated by Django 4.2.1 on 2023-06-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0010_remove_agendamento_curso_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='predio',
            name='Endereco',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='predio',
            name='Telefone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
