# Generated by Django 4.2.1 on 2023-06-06 12:54

from django.db import migrations, models
from django.contrib.auth.models import AbstractUser




class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0011_predio_endereco_predio_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Matricula',
            field=models.CharField(max_length=15, unique=True),
        ),

    ]



