# Generated by Django 4.2.1 on 2023-06-06 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0012_alter_funcionario_cpf_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='Agendado',
            new_name='EstaAgendado',
        ),
    ]
