# Generated by Django 4.2.1 on 2023-06-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0013_rename_agendado_agendamento_estaagendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='Esta_ativa',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
