# Generated by Django 4.2.1 on 2023-07-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0014_salas_esta_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosenac',
            name='Nome',
            field=models.CharField(max_length=20, verbose_name='Curso/Setor'),
        ),
    ]
