# Generated by Django 4.2.1 on 2023-07-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0015_alter_cursosenac_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='Curso_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.cursosenac', verbose_name='Curso/Setor'),
        ),
    ]
