# Generated by Django 4.2.1 on 2023-07-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BancoDeDados', '0016_alter_funcionario_curso_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursosenac',
            name='Nome',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='Curso_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BancoDeDados.cursosenac'),
        ),
    ]
